const USER_MANAGEMENT_TEST_IDS = Object.freeze({
  screen: 'user-management-screen',
  forbidden: 'user-management-forbidden',
  userSearch: 'user-management-user-search',
  facilitySearch: 'user-management-facility-search',
  userRoleFilter: 'user-management-user-role-filter',
  userStatusFilter: 'user-management-user-status-filter',
  clearFilters: 'user-management-clear-filters',
  summary: 'user-management-summary',
  createForm: 'user-management-create-form',
  userList: 'user-management-user-list',
  userItem: 'user-management-user-item',
  facilityList: 'user-management-facility-list',
  facilityItem: 'user-management-facility-item',
  facilitySelected: 'user-management-facility-selected',
  assignmentForm: 'user-management-assignment-form',
  assign: 'user-management-assign',
  create: 'user-management-create',
  refresh: 'user-management-refresh',
  notice: 'user-management-notice',
  userStatusActivate: 'user-management-user-status-activate',
  userStatusSuspend: 'user-management-user-status-suspend',
  userStatusDeactivate: 'user-management-user-status-deactivate',
  userStatusSaved: 'user-management-user-status-saved',
  membershipRole: 'user-management-membership-role',
  membershipApprove: 'user-management-membership-approve',
  membershipSuspend: 'user-management-membership-suspend',
  membershipDeactivate: 'user-management-membership-deactivate',
  membershipSaved: 'user-management-membership-saved',
});

export { USER_MANAGEMENT_TEST_IDS };
