/**
 * Curated Uganda hospital options for registration-time facility affiliation.
 * This is seed UI data only; selected facilities are still verified through backend governance.
 * File: ugandaHospitals.js
 */

const hospital = (id, name, district, region, type, ownership, aliases = []) => Object.freeze({
  id,
  name,
  district,
  region,
  type,
  ownership,
  aliases: Object.freeze(aliases),
});

export const UGANDA_HOSPITALS = Object.freeze([
  hospital('ug-hospital-001', 'Butabika National Referral Hospital', 'Kampala', 'Central', 'National referral hospital', 'Government'),
  hospital('ug-hospital-002', 'Mulago National Referral Hospital', 'Kampala', 'Central', 'National referral hospital', 'Government'),
  hospital('ug-hospital-003', 'Mulago National Specialised Hospital', 'Kampala', 'Central', 'Specialized hospital', 'Government'),
  hospital('ug-hospital-004', 'Mulago Womens Referral Hospital', 'Kampala', 'Central', 'Specialized hospital', 'Government'),
  hospital('ug-hospital-005', 'Uganda Cancer Institute', 'Kampala', 'Central', 'Specialized hospital', 'Government'),
  hospital('ug-hospital-006', 'Uganda Heart Institute', 'Kampala', 'Central', 'Specialized hospital', 'Government'),
  hospital('ug-hospital-007', 'Arua Regional Referral Hospital', 'Arua', 'Northern', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-008', 'Entebbe Regional Referral Hospital', 'Wakiso', 'Central', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-009', 'Fort Portal Regional Referral Hospital', 'Kabarole', 'Western', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-010', 'Gulu Regional Referral Hospital', 'Gulu', 'Northern', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-011', 'Hoima Regional Referral Hospital', 'Hoima', 'Western', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-012', 'Jinja Regional Referral Hospital', 'Jinja', 'Eastern', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-013', 'Kabale Regional Referral Hospital', 'Kabale', 'Western', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-014', 'Kayunga Regional Referral Hospital', 'Kayunga', 'Central', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-015', 'Lira Regional Referral Hospital', 'Lira', 'Northern', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-016', 'Masaka Regional Referral Hospital', 'Masaka', 'Central', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-017', 'Mbale Regional Referral Hospital', 'Mbale', 'Eastern', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-018', 'Mbarara Regional Referral Hospital', 'Mbarara', 'Western', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-019', 'Moroto Regional Referral Hospital', 'Moroto', 'Northern', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-020', 'Mubende Regional Referral Hospital', 'Mubende', 'Central', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-021', 'Soroti Regional Referral Hospital', 'Soroti', 'Eastern', 'Regional referral hospital', 'Government'),
  hospital('ug-hospital-022', 'Abim General Hospital', 'Abim', 'Northern', 'General hospital', 'Government'),
  hospital('ug-hospital-023', 'Adjumani General Hospital', 'Adjumani', 'Northern', 'General hospital', 'Government'),
  hospital('ug-hospital-024', 'Anaka General Hospital', 'Nwoya', 'Northern', 'General hospital', 'Government'),
  hospital('ug-hospital-025', 'Apac General Hospital', 'Apac', 'Northern', 'General hospital', 'Government'),
  hospital('ug-hospital-026', 'Atutur General Hospital', 'Kumi', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-027', 'Bududa General Hospital', 'Bududa', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-028', 'Bugiri General Hospital', 'Bugiri', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-029', 'Bukwo General Hospital', 'Bukwo', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-030', 'Bundibugyo General Hospital', 'Bundibugyo', 'Western', 'General hospital', 'Government'),
  hospital('ug-hospital-031', 'Busolwe General Hospital', 'Butaleja', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-032', 'Gombe General Hospital', 'Butambala', 'Central', 'General hospital', 'Government'),
  hospital('ug-hospital-033', 'Iganga General Hospital', 'Iganga', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-034', 'Itojo Hospital', 'Ntungamo', 'Western', 'General hospital', 'Government'),
  hospital('ug-hospital-035', 'Kaabong General Hospital', 'Kaabong', 'Northern', 'General hospital', 'Government'),
  hospital('ug-hospital-036', 'Kagadi General Hospital', 'Kagadi', 'Western', 'General hospital', 'Government'),
  hospital('ug-hospital-037', 'Kalisizo General Hospital', 'Kyotera', 'Central', 'General hospital', 'Government'),
  hospital('ug-hospital-038', 'Kamuli General Hospital', 'Kamuli', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-039', 'Kapchorwa General Hospital', 'Kapchorwa', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-040', 'Katakwi General Hospital', 'Katakwi', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-041', 'Kawolo General Hospital', 'Buikwe', 'Central', 'General hospital', 'Government'),
  hospital('ug-hospital-042', 'Kiboga General Hospital', 'Kiboga', 'Central', 'General hospital', 'Government'),
  hospital('ug-hospital-043', 'Kiryandongo General Hospital', 'Kiryandongo', 'Western', 'General hospital', 'Government'),
  hospital('ug-hospital-044', 'Kitagata General Hospital', 'Sheema', 'Western', 'General hospital', 'Government'),
  hospital('ug-hospital-045', 'Kitgum Hospital', 'Kitgum', 'Northern', 'General hospital', 'Government'),
  hospital('ug-hospital-046', 'Kyenjojo General Hospital', 'Kyenjojo', 'Western', 'General hospital', 'Government'),
  hospital('ug-hospital-047', 'Lyantonde General Hospital', 'Lyantonde', 'Central', 'General hospital', 'Government'),
  hospital('ug-hospital-048', 'Masafu General Hospital', 'Busia', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-049', 'Masindi General Hospital', 'Masindi', 'Western', 'General hospital', 'Government'),
  hospital('ug-hospital-050', 'Mityana Hospital', 'Mityana', 'Central', 'General hospital', 'Government'),
  hospital('ug-hospital-051', 'Moyo General Hospital', 'Moyo', 'Northern', 'General hospital', 'Government'),
  hospital('ug-hospital-052', 'Mpigi Hospital', 'Mpigi', 'Central', 'General hospital', 'Government'),
  hospital('ug-hospital-053', 'Mukono General Hospital', 'Mukono', 'Central', 'General hospital', 'Government'),
  hospital('ug-hospital-054', 'Nakaseke General Hospital', 'Nakaseke', 'Central', 'General hospital', 'Government'),
  hospital('ug-hospital-055', 'Nebbi General Hospital', 'Nebbi', 'Northern', 'General hospital', 'Government'),
  hospital('ug-hospital-056', 'Pallisa General Hospital', 'Pallisa', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-057', 'Rakai General Hospital', 'Rakai', 'Central', 'General hospital', 'Government'),
  hospital('ug-hospital-058', 'Tororo General Hospital', 'Tororo', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-059', 'Yumbe General Hospital', 'Yumbe', 'Northern', 'General hospital', 'Government'),
  hospital('ug-hospital-060', 'Buwenge General Hospital', 'Jinja', 'Eastern', 'General hospital', 'Government'),
  hospital('ug-hospital-061', 'Bwera General Hospital', 'Kasese', 'Western', 'General hospital', 'Government'),
  hospital('ug-hospital-062', 'Entebbe General Hospital', 'Wakiso', 'Central', 'General hospital', 'Government'),
  hospital('ug-hospital-063', 'Kawempe National Referral Hospital', 'Kampala', 'Central', 'National referral hospital', 'Government'),
  hospital('ug-hospital-064', 'Kiruddu National Referral Hospital', 'Kampala', 'Central', 'National referral hospital', 'Government'),
  hospital('ug-hospital-065', 'Naguru General Hospital', 'Kampala', 'Central', 'General hospital', 'Government'),
  hospital('ug-hospital-066', 'Bombo Military Hospital', 'Luweero', 'Central', 'Military hospital', 'Government'),
  hospital('ug-hospital-067', 'Entebbe Military Hospital', 'Wakiso', 'Central', 'Military hospital', 'Government'),
  hospital('ug-hospital-068', 'Gulu Military Hospital', 'Gulu', 'Northern', 'Military hospital', 'Government'),
  hospital('ug-hospital-069', 'Mbuya Military Hospital', 'Kampala', 'Central', 'Military hospital', 'Government'),
  hospital('ug-hospital-070', 'Murchison Bay Hospital', 'Kampala', 'Central', 'Prison hospital', 'Government'),
  hospital('ug-hospital-071', 'Nakasongola Military Hospital', 'Nakasongola', 'Central', 'Military hospital', 'Government'),
  hospital('ug-hospital-072', 'Angal Hospital', 'Nebbi', 'Northern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-073', 'Bishop Ceaser Asili Memorial Hospital', 'Luwero', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-074', 'Buluba Hospital', 'Mayuge', 'Eastern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-075', 'Bwindi Community Hospital', 'Kanungu', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-076', 'CoRSU Rehabilitation Hospital', 'Wakiso', 'Central', 'Specialized hospital', 'Private not-for-profit'),
  hospital('ug-hospital-077', 'CURE Childrens Hospital of Uganda', 'Mbale', 'Eastern', 'Specialized hospital', 'Private not-for-profit'),
  hospital('ug-hospital-078', 'Entebbe Childrens Surgical Hospital', 'Wakiso', 'Central', 'Specialized hospital', 'Private not-for-profit'),
  hospital('ug-hospital-079', 'Galilee Community General Jewish Hospital of Uganda', 'Mbale', 'Eastern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-080', 'Holy Family Hospital Nyapea', 'Zombo', 'Northern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-081', 'Holy Innocents Childrens Hospital', 'Mbarara', 'Western', 'Specialized hospital', 'Private not-for-profit'),
  hospital('ug-hospital-082', 'Ishaka Adventist Hospital', 'Bushenyi', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-083', 'Kagando Hospital', 'Kasese', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-084', 'Kalongo Hospital', 'Agago', 'Northern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-085', 'Kamuli Mission Hospital', 'Kamuli', 'Eastern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-086', 'Kilembe Mines Hospital', 'Kasese', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-087', 'Kisiizi Hospital', 'Rukungiri', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-088', 'Kisubi Hospital', 'Wakiso', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-089', 'Kitovu Hospital', 'Masaka', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-090', 'Kiwoko Hospital', 'Nakaseke', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-091', 'Lacor Hospital', 'Gulu', 'Northern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-092', 'Lubaga Hospital', 'Kampala', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-093', 'Mengo Hospital', 'Kampala', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-094', 'Mildmay Uganda Hospital', 'Wakiso', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-095', 'Mutolere Hospital', 'Kisoro', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-096', 'Nsambya Hospital', 'Kampala', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-097', 'Nakasero Hospital', 'Kampala', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-098', 'International Hospital Kampala', 'Kampala', 'Central', 'Hospital', 'Private for-profit', ['IHK', 'C-Care IHK']),
  hospital('ug-hospital-099', 'Case Medical Centre', 'Kampala', 'Central', 'Hospital', 'Private for-profit', ['Case Hospital', 'Case Medical Center']),
  hospital('ug-hospital-100', 'Kampala Hospital', 'Kampala', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-101', 'Kitojo Hospital', 'Kyenjojo', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-102', 'Kuluva Hospital', 'Arua', 'Northern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-103', 'Lwala Hospital Kaberamaido', 'Kaberamaido', 'Eastern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-104', 'Makerere University Hospital', 'Kampala', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-105', 'Matany Hospital', 'Napak', 'Northern', 'Hospital', 'Private not-for-profit', ['St. Kizito Hospital Matany']),
  hospital('ug-hospital-106', 'Mayanja Memorial Hospital', 'Mbarara', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-107', 'Naggalama Hospital', 'Mukono', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-108', 'Ngora Hospital', 'Ngora', 'Eastern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-109', 'Nkokonjeru Hospital', 'Buikwe', 'Central', 'Hospital', 'Private not-for-profit', ['St. Francis Hospital Nkokonjeru']),
  hospital('ug-hospital-110', 'Nkozi Hospital', 'Mpigi', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-111', 'Nyenga Mission Hospital', 'Buikwe', 'Central', 'Hospital', 'Private not-for-profit', ['St. Francis Hospital Nyenga']),
  hospital('ug-hospital-112', 'Pope Johns Hospital Aber', 'Oyam', 'Northern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-113', 'Restoration Gateway Hospital', 'Kiryandongo', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-114', 'Ruharo Mission Hospital', 'Mbarara', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-115', 'Rushere Community Hospital', 'Kiruhura', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-116', 'St. Charles Lwanga Buikwe Hospital', 'Buikwe', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-117', 'St. Josephs Hospital Kitgum', 'Kitgum', 'Northern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-118', 'St. Josephs Hospital Maracha', 'Maracha', 'Northern', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-119', 'Uganda Martyrs Hospital Ibanda', 'Ibanda', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-120', 'Villa Maria Hospital', 'Kalungu', 'Central', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-121', 'Virika Hospital', 'Kabarole', 'Western', 'Hospital', 'Private not-for-profit'),
  hospital('ug-hospital-122', 'Whispers Magical Childrens Hospital', 'Jinja', 'Eastern', 'Specialized hospital', 'Private not-for-profit'),
  hospital('ug-hospital-123', 'Bamu Hospital Limited', 'Sembabule', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-124', 'Bethany Womens and Family Hospital', 'Kampala', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-125', 'Healingway Diagnostic and Fertility Centre', 'Kampala', 'Central', 'Specialized hospital', 'Private for-profit'),
  hospital('ug-hospital-126', 'International Specialized Hospital of Uganda', 'Wakiso', 'Central', 'Specialized hospital', 'Private for-profit', ['ISHU']),
  hospital('ug-hospital-127', 'Kampala International University Teaching Hospital', 'Bushenyi', 'Western', 'Teaching hospital', 'Private for-profit', ['KIU Teaching Hospital']),
  hospital('ug-hospital-128', 'Kampala Medical Chambers Hospital', 'Kampala', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-129', 'Kibuli Muslim Hospital', 'Kampala', 'Central', 'Hospital', 'Private not-for-profit', ['Kibuli Hospital']),
  hospital('ug-hospital-130', 'Kumi Orthopaedic Center', 'Kumi', 'Eastern', 'Specialized hospital', 'Private not-for-profit'),
  hospital('ug-hospital-131', 'Le Memorial Hospital', 'Wakiso', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-132', 'Life Line International Hospital', 'Wakiso', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-133', 'Mbarara Community Hospital', 'Mbarara', 'Western', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-134', 'Medipal International Hospital', 'Kampala', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-135', 'Mukwaya General Hospital', 'Kampala', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-136', 'Nile International Hospital', 'Jinja', 'Eastern', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-137', 'Norvik Hospital', 'Kampala', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-138', 'Old Kampala Hospital', 'Kampala', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-139', 'Paragon Hospital', 'Kampala', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-140', 'TMR International Hospital', 'Kampala', 'Central', 'Hospital', 'Private for-profit'),
  hospital('ug-hospital-141', 'UMC Victoria Hospital', 'Kampala', 'Central', 'Hospital', 'Private for-profit', ['Victoria Hospital']),
  hospital('ug-hospital-142', 'Womens Hospital International and Fertility Centre', 'Kampala', 'Central', 'Specialized hospital', 'Private for-profit'),
]);

const normalize = (value) => String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

const hospitalSearchText = (item) => normalize([
  item.name,
  item.district,
  item.region,
  item.type,
  item.ownership,
  ...(Array.isArray(item.aliases) ? item.aliases : []),
].filter(Boolean).join(' '));

export const searchUgandaHospitals = (query = '', limit = 25) => {
  const normalizedQuery = normalize(query);
  const matches = normalizedQuery
    ? UGANDA_HOSPITALS.filter((item) => hospitalSearchText(item).includes(normalizedQuery))
    : UGANDA_HOSPITALS;

  return matches.slice(0, limit);
};

export const getUgandaHospitalById = (id) =>
  UGANDA_HOSPITALS.find((item) => item.id === id) || null;
