-- Drop existing foreign keys before renaming referenced tables and columns.
ALTER TABLE `RefreshSession` DROP FOREIGN KEY `RefreshSession_userId_fkey`;
ALTER TABLE `OnboardingState` DROP FOREIGN KEY `OnboardingState_userId_fkey`;
ALTER TABLE `OnboardingState` DROP FOREIGN KEY `OnboardingState_selectedFacilityId_fkey`;
ALTER TABLE `UserSettings` DROP FOREIGN KEY `UserSettings_userId_fkey`;
ALTER TABLE `UserSettings` DROP FOREIGN KEY `UserSettings_activeFacilityId_fkey`;
ALTER TABLE `FacilitySettings` DROP FOREIGN KEY `FacilitySettings_facilityId_fkey`;
ALTER TABLE `FacilityMembership` DROP FOREIGN KEY `FacilityMembership_userId_fkey`;
ALTER TABLE `FacilityMembership` DROP FOREIGN KEY `FacilityMembership_facilityId_fkey`;
ALTER TABLE `FacilityMembership` DROP FOREIGN KEY `FacilityMembership_approvedByUserId_fkey`;
ALTER TABLE `Patient` DROP FOREIGN KEY `Patient_facilityId_fkey`;
ALTER TABLE `Admission` DROP FOREIGN KEY `Admission_patientId_fkey`;
ALTER TABLE `Admission` DROP FOREIGN KEY `Admission_facilityId_fkey`;
ALTER TABLE `Admission` DROP FOREIGN KEY `Admission_createdByUserId_fkey`;
ALTER TABLE `ClinicalSnapshot` DROP FOREIGN KEY `ClinicalSnapshot_admissionId_fkey`;
ALTER TABLE `ClinicalSnapshot` DROP FOREIGN KEY `ClinicalSnapshot_enteredByUserId_fkey`;
ALTER TABLE `AbgTest` DROP FOREIGN KEY `AbgTest_admissionId_fkey`;
ALTER TABLE `AbgTest` DROP FOREIGN KEY `AbgTest_enteredByUserId_fkey`;
ALTER TABLE `AbgTest` DROP FOREIGN KEY `AbgTest_reviewedByUserId_fkey`;
ALTER TABLE `VentilatorSetting` DROP FOREIGN KEY `VentilatorSetting_admissionId_fkey`;
ALTER TABLE `VentilatorSetting` DROP FOREIGN KEY `VentilatorSetting_enteredByUserId_fkey`;
ALTER TABLE `AirwayDevice` DROP FOREIGN KEY `AirwayDevice_admissionId_fkey`;
ALTER TABLE `AirwayDevice` DROP FOREIGN KEY `AirwayDevice_enteredByUserId_fkey`;
ALTER TABLE `HumidificationDecision` DROP FOREIGN KEY `HumidificationDecision_admissionId_fkey`;
ALTER TABLE `HumidificationDecision` DROP FOREIGN KEY `HumidificationDecision_confirmedByUserId_fkey`;
ALTER TABLE `DailyVentilationReview` DROP FOREIGN KEY `DailyVentilationReview_admissionId_fkey`;
ALTER TABLE `DailyVentilationReview` DROP FOREIGN KEY `DailyVentilationReview_reviewedByUserId_fkey`;
ALTER TABLE `Outcome` DROP FOREIGN KEY `Outcome_admissionId_fkey`;
ALTER TABLE `Outcome` DROP FOREIGN KEY `Outcome_enteredByUserId_fkey`;
ALTER TABLE `ReviewAction` DROP FOREIGN KEY `ReviewAction_facilityId_fkey`;
ALTER TABLE `ReviewAction` DROP FOREIGN KEY `ReviewAction_reviewerUserId_fkey`;
ALTER TABLE `DatasetCase` DROP FOREIGN KEY `DatasetCase_facilityId_fkey`;
ALTER TABLE `DatasetCase` DROP FOREIGN KEY `DatasetCase_sourceAdmissionId_fkey`;
ALTER TABLE `DatasetCase` DROP FOREIGN KEY `DatasetCase_approvedByUserId_fkey`;
ALTER TABLE `DatasetCase` DROP FOREIGN KEY `DatasetCase_reviewedByUserId_fkey`;
ALTER TABLE `ReferenceRule` DROP FOREIGN KEY `ReferenceRule_facilityId_fkey`;
ALTER TABLE `ReferenceRule` DROP FOREIGN KEY `ReferenceRule_approvedByUserId_fkey`;
ALTER TABLE `ReferenceRule` DROP FOREIGN KEY `ReferenceRule_verifiedByUserId_fkey`;
ALTER TABLE `ModelOutput` DROP FOREIGN KEY `ModelOutput_modelVersionId_fkey`;
ALTER TABLE `ModelOutput` DROP FOREIGN KEY `ModelOutput_sourceAdmissionId_fkey`;
ALTER TABLE `IdempotencyRecord` DROP FOREIGN KEY `IdempotencyRecord_userId_fkey`;
ALTER TABLE `IdempotencyRecord` DROP FOREIGN KEY `IdempotencyRecord_facilityId_fkey`;
ALTER TABLE `SyncEvent` DROP FOREIGN KEY `SyncEvent_userId_fkey`;
ALTER TABLE `SyncEvent` DROP FOREIGN KEY `SyncEvent_facilityId_fkey`;
ALTER TABLE `AuditLog` DROP FOREIGN KEY `AuditLog_userId_fkey`;
ALTER TABLE `AuditLog` DROP FOREIGN KEY `AuditLog_facilityId_fkey`;

-- Rename columns to lowercase_snake names while preserving Prisma field names.
ALTER TABLE `User` RENAME COLUMN `passwordHash` TO `password_hash`;
ALTER TABLE `User` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `User` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `RefreshSession` RENAME COLUMN `userId` TO `user_id`;
ALTER TABLE `RefreshSession` RENAME COLUMN `tokenHash` TO `token_hash`;
ALTER TABLE `RefreshSession` RENAME COLUMN `expiresAt` TO `expires_at`;
ALTER TABLE `RefreshSession` RENAME COLUMN `revokedAt` TO `revoked_at`;
ALTER TABLE `RefreshSession` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `RefreshSession` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `OnboardingState` RENAME COLUMN `userId` TO `user_id`;
ALTER TABLE `OnboardingState` RENAME COLUMN `currentStep` TO `current_step`;
ALTER TABLE `OnboardingState` RENAME COLUMN `completedStepsJson` TO `completed_steps_json`;
ALTER TABLE `OnboardingState` RENAME COLUMN `selectedFacilityId` TO `selected_facility_id`;
ALTER TABLE `OnboardingState` RENAME COLUMN `requestedRole` TO `requested_role`;
ALTER TABLE `OnboardingState` RENAME COLUMN `clinicalSafetyAcknowledgedAt` TO `clinical_safety_acknowledged_at`;
ALTER TABLE `OnboardingState` RENAME COLUMN `clinicalSafetyAcknowledgementVersion` TO `clinical_safety_acknowledgement_version`;
ALTER TABLE `OnboardingState` RENAME COLUMN `clinicalSafetyStatementHash` TO `clinical_safety_statement_hash`;
ALTER TABLE `OnboardingState` RENAME COLUMN `completedAt` TO `completed_at`;
ALTER TABLE `OnboardingState` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `OnboardingState` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `Facility` RENAME COLUMN `registryCode` TO `registry_code`;
ALTER TABLE `Facility` RENAME COLUMN `verificationStatus` TO `verification_status`;
ALTER TABLE `Facility` RENAME COLUMN `oxygenProfileJson` TO `oxygen_profile_json`;
ALTER TABLE `Facility` RENAME COLUMN `ventilatorProfileJson` TO `ventilator_profile_json`;
ALTER TABLE `Facility` RENAME COLUMN `abgAvailability` TO `abg_availability`;
ALTER TABLE `Facility` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `Facility` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `UserSettings` RENAME COLUMN `userId` TO `user_id`;
ALTER TABLE `UserSettings` RENAME COLUMN `activeFacilityId` TO `active_facility_id`;
ALTER TABLE `UserSettings` RENAME COLUMN `roleVisibilityJson` TO `role_visibility_json`;
ALTER TABLE `UserSettings` RENAME COLUMN `offlineSyncPreferencesJson` TO `offline_sync_preferences_json`;
ALTER TABLE `UserSettings` RENAME COLUMN `privacyControlsJson` TO `privacy_controls_json`;
ALTER TABLE `UserSettings` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `UserSettings` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `FacilitySettings` RENAME COLUMN `facilityId` TO `facility_id`;
ALTER TABLE `FacilitySettings` RENAME COLUMN `referenceSettingsJson` TO `reference_settings_json`;
ALTER TABLE `FacilitySettings` RENAME COLUMN `workflowSettingsJson` TO `workflow_settings_json`;
ALTER TABLE `FacilitySettings` RENAME COLUMN `privacyControlsJson` TO `privacy_controls_json`;
ALTER TABLE `FacilitySettings` RENAME COLUMN `governanceSettingsJson` TO `governance_settings_json`;
ALTER TABLE `FacilitySettings` RENAME COLUMN `modelVisibilityJson` TO `model_visibility_json`;
ALTER TABLE `FacilitySettings` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `FacilitySettings` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `FacilityMembership` RENAME COLUMN `userId` TO `user_id`;
ALTER TABLE `FacilityMembership` RENAME COLUMN `facilityId` TO `facility_id`;
ALTER TABLE `FacilityMembership` RENAME COLUMN `approvedByUserId` TO `approved_by_user_id`;
ALTER TABLE `FacilityMembership` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `FacilityMembership` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `Patient` RENAME COLUMN `facilityId` TO `facility_id`;
ALTER TABLE `Patient` RENAME COLUMN `appPatientCode` TO `app_patient_code`;
ALTER TABLE `Patient` RENAME COLUMN `optionalName` TO `optional_name`;
ALTER TABLE `Patient` RENAME COLUMN `hospitalNumber` TO `hospital_number`;
ALTER TABLE `Patient` RENAME COLUMN `patientPathway` TO `patient_pathway`;
ALTER TABLE `Patient` RENAME COLUMN `dateOfBirth` TO `date_of_birth`;
ALTER TABLE `Patient` RENAME COLUMN `ageYears` TO `age_years`;
ALTER TABLE `Patient` RENAME COLUMN `ageMonths` TO `age_months`;
ALTER TABLE `Patient` RENAME COLUMN `estimatedAge` TO `estimated_age`;
ALTER TABLE `Patient` RENAME COLUMN `gestationalAgeWeeks` TO `gestational_age_weeks`;
ALTER TABLE `Patient` RENAME COLUMN `correctedAgeWeeks` TO `corrected_age_weeks`;
ALTER TABLE `Patient` RENAME COLUMN `sexForSizeCalculations` TO `sex_for_size_calculations`;
ALTER TABLE `Patient` RENAME COLUMN `actualWeightKg` TO `actual_weight_kg`;
ALTER TABLE `Patient` RENAME COLUMN `heightOrLengthCm` TO `height_or_length_cm`;
ALTER TABLE `Patient` RENAME COLUMN `referenceWeightKg` TO `reference_weight_kg`;
ALTER TABLE `Patient` RENAME COLUMN `referenceWeightMethod` TO `reference_weight_method`;
ALTER TABLE `Patient` RENAME COLUMN `pathwayDetailsJson` TO `pathway_details_json`;
ALTER TABLE `Patient` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `Patient` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `Admission` RENAME COLUMN `patientId` TO `patient_id`;
ALTER TABLE `Admission` RENAME COLUMN `facilityId` TO `facility_id`;
ALTER TABLE `Admission` RENAME COLUMN `appAdmissionCode` TO `app_admission_code`;
ALTER TABLE `Admission` RENAME COLUMN `bedNumber` TO `bed_number`;
ALTER TABLE `Admission` RENAME COLUMN `admittedAt` TO `admitted_at`;
ALTER TABLE `Admission` RENAME COLUMN `admissionSource` TO `admission_source`;
ALTER TABLE `Admission` RENAME COLUMN `reasonForVentilation` TO `reason_for_ventilation`;
ALTER TABLE `Admission` RENAME COLUMN `createdByUserId` TO `created_by_user_id`;
ALTER TABLE `Admission` RENAME COLUMN `reviewStatus` TO `review_status`;
ALTER TABLE `Admission` RENAME COLUMN `clientRecordId` TO `client_record_id`;
ALTER TABLE `Admission` RENAME COLUMN `deviceId` TO `device_id`;
ALTER TABLE `Admission` RENAME COLUMN `clientCreatedAt` TO `client_created_at`;
ALTER TABLE `Admission` RENAME COLUMN `clientUpdatedAt` TO `client_updated_at`;
ALTER TABLE `Admission` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `Admission` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `admissionId` TO `admission_id`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `measuredAt` TO `measured_at`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `oxygenSupportType` TO `oxygen_support_type`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `heartRate` TO `heart_rate`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `respiratoryRate` TO `respiratory_rate`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `systolicBp` TO `systolic_bp`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `diastolicBp` TO `diastolic_bp`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `meanArterialPressure` TO `mean_arterial_pressure`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `temperatureC` TO `temperature_c`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `mainCondition` TO `main_condition`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `comorbiditiesJson` TO `comorbidities_json`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `validationStatus` TO `validation_status`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `enteredByUserId` TO `entered_by_user_id`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `clientRecordId` TO `client_record_id`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `deviceId` TO `device_id`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `clientCreatedAt` TO `client_created_at`;
ALTER TABLE `ClinicalSnapshot` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `AbgTest` RENAME COLUMN `admissionId` TO `admission_id`;
ALTER TABLE `AbgTest` RENAME COLUMN `collectedAt` TO `collected_at`;
ALTER TABLE `AbgTest` RENAME COLUMN `baseExcess` TO `base_excess`;
ALTER TABLE `AbgTest` RENAME COLUMN `fio2AtSample` TO `fio2_at_sample`;
ALTER TABLE `AbgTest` RENAME COLUMN `spo2AtSample` TO `spo2_at_sample`;
ALTER TABLE `AbgTest` RENAME COLUMN `validationStatus` TO `validation_status`;
ALTER TABLE `AbgTest` RENAME COLUMN `clinicalFlagsJson` TO `clinical_flags_json`;
ALTER TABLE `AbgTest` RENAME COLUMN `calculationSummaryJson` TO `calculation_summary_json`;
ALTER TABLE `AbgTest` RENAME COLUMN `enteredByUserId` TO `entered_by_user_id`;
ALTER TABLE `AbgTest` RENAME COLUMN `reviewedByUserId` TO `reviewed_by_user_id`;
ALTER TABLE `AbgTest` RENAME COLUMN `reviewStatus` TO `review_status`;
ALTER TABLE `AbgTest` RENAME COLUMN `clientRecordId` TO `client_record_id`;
ALTER TABLE `AbgTest` RENAME COLUMN `deviceId` TO `device_id`;
ALTER TABLE `AbgTest` RENAME COLUMN `clientCreatedAt` TO `client_created_at`;
ALTER TABLE `AbgTest` RENAME COLUMN `clientUpdatedAt` TO `client_updated_at`;
ALTER TABLE `AbgTest` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `admissionId` TO `admission_id`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `measuredAt` TO `measured_at`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `tidalVolumeMl` TO `tidal_volume_ml`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `respiratoryRateSet` TO `respiratory_rate_set`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `respiratoryRateMeasured` TO `respiratory_rate_measured`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `pressureSupport` TO `pressure_support`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `inspiratoryPressure` TO `inspiratory_pressure`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `peakPressure` TO `peak_pressure`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `plateauPressure` TO `plateau_pressure`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `ieRatio` TO `ie_ratio`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `minuteVolumeLMin` TO `minute_volume_l_min`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `vtMlPerKgReferenceWeight` TO `vt_ml_per_kg_reference_weight`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `drivingPressure` TO `driving_pressure`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `validationStatus` TO `validation_status`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `clinicalFlagsJson` TO `clinical_flags_json`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `calculationSummaryJson` TO `calculation_summary_json`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `enteredByUserId` TO `entered_by_user_id`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `reviewStatus` TO `review_status`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `clientRecordId` TO `client_record_id`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `deviceId` TO `device_id`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `clientCreatedAt` TO `client_created_at`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `clientUpdatedAt` TO `client_updated_at`;
ALTER TABLE `VentilatorSetting` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `admissionId` TO `admission_id`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `measuredAt` TO `measured_at`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `airwayRoute` TO `airway_route`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `tubeType` TO `tube_type`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `internalDiameterMm` TO `internal_diameter_mm`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `depthCm` TO `depth_cm`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `cuffPressureCmH2O` TO `cuff_pressure_cm_h2o`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `tubeSecured` TO `tube_secured`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `validationStatus` TO `validation_status`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `clinicalFlagsJson` TO `clinical_flags_json`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `enteredByUserId` TO `entered_by_user_id`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `clientRecordId` TO `client_record_id`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `deviceId` TO `device_id`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `clientCreatedAt` TO `client_created_at`;
ALTER TABLE `AirwayDevice` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `admissionId` TO `admission_id`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `measuredAt` TO `measured_at`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `thickSecretions` TO `thick_secretions`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `highMinuteVentilation` TO `high_minute_ventilation`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `airwayBleeding` TO `airway_bleeding`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `expectedLongVentilation` TO `expected_long_ventilation`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `suggestedOption` TO `suggested_option`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `confirmedOption` TO `confirmed_option`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `clinicalFlagsJson` TO `clinical_flags_json`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `confirmedByUserId` TO `confirmed_by_user_id`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `clientRecordId` TO `client_record_id`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `deviceId` TO `device_id`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `clientCreatedAt` TO `client_created_at`;
ALTER TABLE `HumidificationDecision` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `admissionId` TO `admission_id`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `reviewDate` TO `review_date`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `oxygenationStable` TO `oxygenation_stable`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `hemodynamicsStable` TO `hemodynamics_stable`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `sedationLightEnough` TO `sedation_light_enough`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `secretionsManageable` TO `secretions_manageable`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `sbtStatus` TO `sbt_status`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `sbtFailureReason` TO `sbt_failure_reason`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `proneStatus` TO `prone_status`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `vapBundleJson` TO `vap_bundle_json`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `clinicalFlagsJson` TO `clinical_flags_json`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `reviewedByUserId` TO `reviewed_by_user_id`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `clientRecordId` TO `client_record_id`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `deviceId` TO `device_id`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `clientCreatedAt` TO `client_created_at`;
ALTER TABLE `DailyVentilationReview` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `Outcome` RENAME COLUMN `admissionId` TO `admission_id`;
ALTER TABLE `Outcome` RENAME COLUMN `outcomeType` TO `outcome_type`;
ALTER TABLE `Outcome` RENAME COLUMN `outcomeDate` TO `outcome_date`;
ALTER TABLE `Outcome` RENAME COLUMN `ventilatorDays` TO `ventilator_days`;
ALTER TABLE `Outcome` RENAME COLUMN `icuLengthOfStayDays` TO `icu_length_of_stay_days`;
ALTER TABLE `Outcome` RENAME COLUMN `hospitalLengthOfStayDays` TO `hospital_length_of_stay_days`;
ALTER TABLE `Outcome` RENAME COLUMN `reintubationWithin48h` TO `reintubation_within_48h`;
ALTER TABLE `Outcome` RENAME COLUMN `vapSuspected` TO `vap_suspected`;
ALTER TABLE `Outcome` RENAME COLUMN `enteredByUserId` TO `entered_by_user_id`;
ALTER TABLE `Outcome` RENAME COLUMN `clientRecordId` TO `client_record_id`;
ALTER TABLE `Outcome` RENAME COLUMN `deviceId` TO `device_id`;
ALTER TABLE `Outcome` RENAME COLUMN `clientCreatedAt` TO `client_created_at`;
ALTER TABLE `Outcome` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `ReviewAction` RENAME COLUMN `facilityId` TO `facility_id`;
ALTER TABLE `ReviewAction` RENAME COLUMN `reviewerUserId` TO `reviewer_user_id`;
ALTER TABLE `ReviewAction` RENAME COLUMN `entityType` TO `entity_type`;
ALTER TABLE `ReviewAction` RENAME COLUMN `entityId` TO `entity_id`;
ALTER TABLE `ReviewAction` RENAME COLUMN `statusBefore` TO `status_before`;
ALTER TABLE `ReviewAction` RENAME COLUMN `statusAfter` TO `status_after`;
ALTER TABLE `ReviewAction` RENAME COLUMN `validationStatus` TO `validation_status`;
ALTER TABLE `ReviewAction` RENAME COLUMN `triagePriority` TO `triage_priority`;
ALTER TABLE `ReviewAction` RENAME COLUMN `overrideReason` TO `override_reason`;
ALTER TABLE `ReviewAction` RENAME COLUMN `correctionJson` TO `correction_json`;
ALTER TABLE `ReviewAction` RENAME COLUMN `returnedToClinician` TO `returned_to_clinician`;
ALTER TABLE `ReviewAction` RENAME COLUMN `beforeJson` TO `before_json`;
ALTER TABLE `ReviewAction` RENAME COLUMN `afterJson` TO `after_json`;
ALTER TABLE `ReviewAction` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `DatasetCase` RENAME COLUMN `facilityId` TO `facility_id`;
ALTER TABLE `DatasetCase` RENAME COLUMN `sourceAdmissionId` TO `source_admission_id`;
ALTER TABLE `DatasetCase` RENAME COLUMN `sourceType` TO `source_type`;
ALTER TABLE `DatasetCase` RENAME COLUMN `sourcePayloadJson` TO `source_payload_json`;
ALTER TABLE `DatasetCase` RENAME COLUMN `structuredPreviewJson` TO `structured_preview_json`;
ALTER TABLE `DatasetCase` RENAME COLUMN `deidentifiedPayloadJson` TO `deidentified_payload_json`;
ALTER TABLE `DatasetCase` RENAME COLUMN `deidentificationStatus` TO `deidentification_status`;
ALTER TABLE `DatasetCase` RENAME COLUMN `reviewStatus` TO `review_status`;
ALTER TABLE `DatasetCase` RENAME COLUMN `approvedForTraining` TO `approved_for_training`;
ALTER TABLE `DatasetCase` RENAME COLUMN `approvedByUserId` TO `approved_by_user_id`;
ALTER TABLE `DatasetCase` RENAME COLUMN `reviewedByUserId` TO `reviewed_by_user_id`;
ALTER TABLE `DatasetCase` RENAME COLUMN `reviewedAt` TO `reviewed_at`;
ALTER TABLE `DatasetCase` RENAME COLUMN `ethicsApprovalId` TO `ethics_approval_id`;
ALTER TABLE `DatasetCase` RENAME COLUMN `governanceJson` TO `governance_json`;
ALTER TABLE `DatasetCase` RENAME COLUMN `datasetVersion` TO `dataset_version`;
ALTER TABLE `DatasetCase` RENAME COLUMN `exclusionReason` TO `exclusion_reason`;
ALTER TABLE `DatasetCase` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `DatasetCase` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `facilityId` TO `facility_id`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `clinicalCondition` TO `clinical_condition`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `patientPathway` TO `patient_pathway`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `parameterName` TO `parameter_name`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `lowerBound` TO `lower_bound`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `upperBound` TO `upper_bound`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `sourceCitation` TO `source_citation`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `ruleJson` TO `rule_json`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `activeFrom` TO `active_from`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `activeTo` TO `active_to`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `approvedByUserId` TO `approved_by_user_id`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `verifiedByUserId` TO `verified_by_user_id`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `verifiedAt` TO `verified_at`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `verificationStatus` TO `verification_status`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `reviewNotes` TO `review_notes`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `auditTrailJson` TO `audit_trail_json`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `governanceStatus` TO `governance_status`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `ReferenceRule` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `ModelVersion` RENAME COLUMN `modelName` TO `model_name`;
ALTER TABLE `ModelVersion` RENAME COLUMN `trainingDatasetVersion` TO `training_dataset_version`;
ALTER TABLE `ModelVersion` RENAME COLUMN `intendedUse` TO `intended_use`;
ALTER TABLE `ModelVersion` RENAME COLUMN `contraindicatedUse` TO `contraindicated_use`;
ALTER TABLE `ModelVersion` RENAME COLUMN `performanceSummaryJson` TO `performance_summary_json`;
ALTER TABLE `ModelVersion` RENAME COLUMN `calibrationSummaryJson` TO `calibration_summary_json`;
ALTER TABLE `ModelVersion` RENAME COLUMN `biasAssessmentJson` TO `bias_assessment_json`;
ALTER TABLE `ModelVersion` RENAME COLUMN `approvalStatus` TO `approval_status`;
ALTER TABLE `ModelVersion` RENAME COLUMN `activatedAt` TO `activated_at`;
ALTER TABLE `ModelVersion` RENAME COLUMN `retiredAt` TO `retired_at`;
ALTER TABLE `ModelVersion` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `ModelVersion` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `ModelOutput` RENAME COLUMN `modelVersionId` TO `model_version_id`;
ALTER TABLE `ModelOutput` RENAME COLUMN `facilityId` TO `facility_id`;
ALTER TABLE `ModelOutput` RENAME COLUMN `sourceAdmissionId` TO `source_admission_id`;
ALTER TABLE `ModelOutput` RENAME COLUMN `inputSummaryJson` TO `input_summary_json`;
ALTER TABLE `ModelOutput` RENAME COLUMN `outputJson` TO `output_json`;
ALTER TABLE `ModelOutput` RENAME COLUMN `visibleToClinicians` TO `visible_to_clinicians`;
ALTER TABLE `ModelOutput` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `IdempotencyRecord` RENAME COLUMN `userId` TO `user_id`;
ALTER TABLE `IdempotencyRecord` RENAME COLUMN `facilityId` TO `facility_id`;
ALTER TABLE `IdempotencyRecord` RENAME COLUMN `requestHash` TO `request_hash`;
ALTER TABLE `IdempotencyRecord` RENAME COLUMN `responseJson` TO `response_json`;
ALTER TABLE `IdempotencyRecord` RENAME COLUMN `entityType` TO `entity_type`;
ALTER TABLE `IdempotencyRecord` RENAME COLUMN `entityId` TO `entity_id`;
ALTER TABLE `IdempotencyRecord` RENAME COLUMN `clientRecordId` TO `client_record_id`;
ALTER TABLE `IdempotencyRecord` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `IdempotencyRecord` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `SyncEvent` RENAME COLUMN `userId` TO `user_id`;
ALTER TABLE `SyncEvent` RENAME COLUMN `facilityId` TO `facility_id`;
ALTER TABLE `SyncEvent` RENAME COLUMN `entityType` TO `entity_type`;
ALTER TABLE `SyncEvent` RENAME COLUMN `entityId` TO `entity_id`;
ALTER TABLE `SyncEvent` RENAME COLUMN `clientRecordId` TO `client_record_id`;
ALTER TABLE `SyncEvent` RENAME COLUMN `idempotencyKey` TO `idempotency_key`;
ALTER TABLE `SyncEvent` RENAME COLUMN `requestPayloadJson` TO `request_payload_json`;
ALTER TABLE `SyncEvent` RENAME COLUMN `responsePayloadJson` TO `response_payload_json`;
ALTER TABLE `SyncEvent` RENAME COLUMN `conflictPayloadJson` TO `conflict_payload_json`;
ALTER TABLE `SyncEvent` RENAME COLUMN `errorMessage` TO `error_message`;
ALTER TABLE `SyncEvent` RENAME COLUMN `clientCreatedAt` TO `client_created_at`;
ALTER TABLE `SyncEvent` RENAME COLUMN `clientUpdatedAt` TO `client_updated_at`;
ALTER TABLE `SyncEvent` RENAME COLUMN `deviceId` TO `device_id`;
ALTER TABLE `SyncEvent` RENAME COLUMN `receivedAt` TO `received_at`;
ALTER TABLE `SyncEvent` RENAME COLUMN `resolvedAt` TO `resolved_at`;
ALTER TABLE `SyncEvent` RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE `SyncEvent` RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE `AuditLog` RENAME COLUMN `userId` TO `user_id`;
ALTER TABLE `AuditLog` RENAME COLUMN `facilityId` TO `facility_id`;
ALTER TABLE `AuditLog` RENAME COLUMN `entityType` TO `entity_type`;
ALTER TABLE `AuditLog` RENAME COLUMN `entityId` TO `entity_id`;
ALTER TABLE `AuditLog` RENAME COLUMN `beforeJson` TO `before_json`;
ALTER TABLE `AuditLog` RENAME COLUMN `afterJson` TO `after_json`;
ALTER TABLE `AuditLog` RENAME COLUMN `requestId` TO `request_id`;
ALTER TABLE `AuditLog` RENAME COLUMN `ipHash` TO `ip_hash`;
ALTER TABLE `AuditLog` RENAME COLUMN `createdAt` TO `created_at`;

-- Rename tables to lowercase_snake names.
RENAME TABLE `User` TO `_snake_rename_user`;
RENAME TABLE `_snake_rename_user` TO `user`;
RENAME TABLE `RefreshSession` TO `_snake_rename_refresh_session`;
RENAME TABLE `_snake_rename_refresh_session` TO `refresh_session`;
RENAME TABLE `OnboardingState` TO `_snake_rename_onboarding_state`;
RENAME TABLE `_snake_rename_onboarding_state` TO `onboarding_state`;
RENAME TABLE `Facility` TO `_snake_rename_facility`;
RENAME TABLE `_snake_rename_facility` TO `facility`;
RENAME TABLE `UserSettings` TO `_snake_rename_user_settings`;
RENAME TABLE `_snake_rename_user_settings` TO `user_settings`;
RENAME TABLE `FacilitySettings` TO `_snake_rename_facility_settings`;
RENAME TABLE `_snake_rename_facility_settings` TO `facility_settings`;
RENAME TABLE `FacilityMembership` TO `_snake_rename_facility_membership`;
RENAME TABLE `_snake_rename_facility_membership` TO `facility_membership`;
RENAME TABLE `Patient` TO `_snake_rename_patient`;
RENAME TABLE `_snake_rename_patient` TO `patient`;
RENAME TABLE `Admission` TO `_snake_rename_admission`;
RENAME TABLE `_snake_rename_admission` TO `admission`;
RENAME TABLE `ClinicalSnapshot` TO `_snake_rename_clinical_snapshot`;
RENAME TABLE `_snake_rename_clinical_snapshot` TO `clinical_snapshot`;
RENAME TABLE `AbgTest` TO `_snake_rename_abg_test`;
RENAME TABLE `_snake_rename_abg_test` TO `abg_test`;
RENAME TABLE `VentilatorSetting` TO `_snake_rename_ventilator_setting`;
RENAME TABLE `_snake_rename_ventilator_setting` TO `ventilator_setting`;
RENAME TABLE `AirwayDevice` TO `_snake_rename_airway_device`;
RENAME TABLE `_snake_rename_airway_device` TO `airway_device`;
RENAME TABLE `HumidificationDecision` TO `_snake_rename_humidification_decision`;
RENAME TABLE `_snake_rename_humidification_decision` TO `humidification_decision`;
RENAME TABLE `DailyVentilationReview` TO `_snake_rename_daily_ventilation_review`;
RENAME TABLE `_snake_rename_daily_ventilation_review` TO `daily_ventilation_review`;
RENAME TABLE `Outcome` TO `_snake_rename_outcome`;
RENAME TABLE `_snake_rename_outcome` TO `outcome`;
RENAME TABLE `ReviewAction` TO `_snake_rename_review_action`;
RENAME TABLE `_snake_rename_review_action` TO `review_action`;
RENAME TABLE `DatasetCase` TO `_snake_rename_dataset_case`;
RENAME TABLE `_snake_rename_dataset_case` TO `dataset_case`;
RENAME TABLE `ReferenceRule` TO `_snake_rename_reference_rule`;
RENAME TABLE `_snake_rename_reference_rule` TO `reference_rule`;
RENAME TABLE `ModelVersion` TO `_snake_rename_model_version`;
RENAME TABLE `_snake_rename_model_version` TO `model_version`;
RENAME TABLE `ModelOutput` TO `_snake_rename_model_output`;
RENAME TABLE `_snake_rename_model_output` TO `model_output`;
RENAME TABLE `IdempotencyRecord` TO `_snake_rename_idempotency_record`;
RENAME TABLE `_snake_rename_idempotency_record` TO `idempotency_record`;
RENAME TABLE `SyncEvent` TO `_snake_rename_sync_event`;
RENAME TABLE `_snake_rename_sync_event` TO `sync_event`;
RENAME TABLE `AuditLog` TO `_snake_rename_audit_log`;
RENAME TABLE `_snake_rename_audit_log` TO `audit_log`;

-- Rename indexes and unique constraints to match the new physical names.
ALTER TABLE `user` RENAME INDEX `User_email_key` TO `user_email_key`;
ALTER TABLE `refresh_session` RENAME INDEX `RefreshSession_tokenHash_key` TO `refresh_session_token_hash_key`;
ALTER TABLE `refresh_session` RENAME INDEX `RefreshSession_userId_revokedAt_idx` TO `refresh_session_user_id_revoked_at_idx`;
ALTER TABLE `refresh_session` RENAME INDEX `RefreshSession_expiresAt_idx` TO `refresh_session_expires_at_idx`;
ALTER TABLE `onboarding_state` RENAME INDEX `OnboardingState_userId_key` TO `onboarding_state_user_id_key`;
ALTER TABLE `onboarding_state` RENAME INDEX `OnboardingState_selectedFacilityId_status_idx` TO `onboarding_state_selected_facility_id_status_idx`;
ALTER TABLE `onboarding_state` RENAME INDEX `OnboardingState_status_currentStep_idx` TO `onboarding_state_status_current_step_idx`;
ALTER TABLE `facility` RENAME INDEX `Facility_registryCode_key` TO `facility_registry_code_key`;
ALTER TABLE `user_settings` RENAME INDEX `UserSettings_userId_key` TO `user_settings_user_id_key`;
ALTER TABLE `user_settings` RENAME INDEX `UserSettings_activeFacilityId_idx` TO `user_settings_active_facility_id_idx`;
ALTER TABLE `facility_settings` RENAME INDEX `FacilitySettings_facilityId_key` TO `facility_settings_facility_id_key`;
ALTER TABLE `facility_membership` RENAME INDEX `FacilityMembership_facilityId_status_idx` TO `facility_membership_facility_id_status_idx`;
ALTER TABLE `facility_membership` RENAME INDEX `FacilityMembership_userId_status_idx` TO `facility_membership_user_id_status_idx`;
ALTER TABLE `facility_membership` RENAME INDEX `FacilityMembership_userId_facilityId_role_key` TO `facility_membership_user_id_facility_id_role_key`;
ALTER TABLE `patient` RENAME INDEX `Patient_facilityId_hospitalNumber_idx` TO `patient_facility_id_hospital_number_idx`;
ALTER TABLE `patient` RENAME INDEX `Patient_facilityId_patientPathway_idx` TO `patient_facility_id_patient_pathway_idx`;
ALTER TABLE `patient` RENAME INDEX `Patient_facilityId_appPatientCode_key` TO `patient_facility_id_app_patient_code_key`;
ALTER TABLE `admission` RENAME INDEX `Admission_facilityId_status_idx` TO `admission_facility_id_status_idx`;
ALTER TABLE `admission` RENAME INDEX `Admission_patientId_idx` TO `admission_patient_id_idx`;
ALTER TABLE `admission` RENAME INDEX `Admission_clientRecordId_idx` TO `admission_client_record_id_idx`;
ALTER TABLE `admission` RENAME INDEX `Admission_facilityId_appAdmissionCode_key` TO `admission_facility_id_app_admission_code_key`;
ALTER TABLE `clinical_snapshot` RENAME INDEX `ClinicalSnapshot_admissionId_measuredAt_idx` TO `clinical_snapshot_admission_id_measured_at_idx`;
ALTER TABLE `clinical_snapshot` RENAME INDEX `ClinicalSnapshot_clientRecordId_idx` TO `clinical_snapshot_client_record_id_idx`;
ALTER TABLE `abg_test` RENAME INDEX `AbgTest_admissionId_collectedAt_idx` TO `abg_test_admission_id_collected_at_idx`;
ALTER TABLE `abg_test` RENAME INDEX `AbgTest_reviewStatus_idx` TO `abg_test_review_status_idx`;
ALTER TABLE `abg_test` RENAME INDEX `AbgTest_clientRecordId_idx` TO `abg_test_client_record_id_idx`;
ALTER TABLE `abg_test` RENAME INDEX `AbgTest_admissionId_version_key` TO `abg_test_admission_id_version_key`;
ALTER TABLE `ventilator_setting` RENAME INDEX `VentilatorSetting_admissionId_measuredAt_idx` TO `ventilator_setting_admission_id_measured_at_idx`;
ALTER TABLE `ventilator_setting` RENAME INDEX `VentilatorSetting_reviewStatus_idx` TO `ventilator_setting_review_status_idx`;
ALTER TABLE `ventilator_setting` RENAME INDEX `VentilatorSetting_clientRecordId_idx` TO `ventilator_setting_client_record_id_idx`;
ALTER TABLE `ventilator_setting` RENAME INDEX `VentilatorSetting_admissionId_version_key` TO `ventilator_setting_admission_id_version_key`;
ALTER TABLE `airway_device` RENAME INDEX `AirwayDevice_admissionId_measuredAt_idx` TO `airway_device_admission_id_measured_at_idx`;
ALTER TABLE `airway_device` RENAME INDEX `AirwayDevice_clientRecordId_idx` TO `airway_device_client_record_id_idx`;
ALTER TABLE `humidification_decision` RENAME INDEX `HumidificationDecision_admissionId_measuredAt_idx` TO `humidification_decision_admission_id_measured_at_idx`;
ALTER TABLE `humidification_decision` RENAME INDEX `HumidificationDecision_clientRecordId_idx` TO `humidification_decision_client_record_id_idx`;
ALTER TABLE `daily_ventilation_review` RENAME INDEX `DailyVentilationReview_admissionId_reviewDate_idx` TO `daily_ventilation_review_admission_id_review_date_idx`;
ALTER TABLE `daily_ventilation_review` RENAME INDEX `DailyVentilationReview_clientRecordId_idx` TO `daily_ventilation_review_client_record_id_idx`;
ALTER TABLE `outcome` RENAME INDEX `Outcome_admissionId_outcomeDate_idx` TO `outcome_admission_id_outcome_date_idx`;
ALTER TABLE `outcome` RENAME INDEX `Outcome_clientRecordId_idx` TO `outcome_client_record_id_idx`;
ALTER TABLE `review_action` RENAME INDEX `ReviewAction_facilityId_entityType_entityId_idx` TO `review_action_facility_id_entity_type_entity_id_idx`;
ALTER TABLE `review_action` RENAME INDEX `ReviewAction_reviewerUserId_createdAt_idx` TO `review_action_reviewer_user_id_created_at_idx`;
ALTER TABLE `dataset_case` RENAME INDEX `DatasetCase_facilityId_reviewStatus_idx` TO `dataset_case_facility_id_review_status_idx`;
ALTER TABLE `dataset_case` RENAME INDEX `DatasetCase_approvedForTraining_datasetVersion_idx` TO `dataset_case_approved_for_training_dataset_version_idx`;
ALTER TABLE `dataset_case` RENAME INDEX `DatasetCase_sourceAdmissionId_idx` TO `dataset_case_source_admission_id_idx`;
ALTER TABLE `reference_rule` RENAME INDEX `ReferenceRule_activeFrom_activeTo_idx` TO `reference_rule_active_from_active_to_idx`;
ALTER TABLE `reference_rule` RENAME INDEX `ReferenceRule_parameterName_patientPathway_population_idx` TO `reference_rule_parameter_name_patient_pathway_population_idx`;
ALTER TABLE `reference_rule` RENAME INDEX `ReferenceRule_facilityId_verificationStatus_idx` TO `reference_rule_facility_id_verification_status_idx`;
ALTER TABLE `reference_rule` RENAME INDEX `ReferenceRule_verificationStatus_activeFrom_activeTo_idx` TO `reference_rule_verification_status_active_from_active_to_idx`;
ALTER TABLE `reference_rule` RENAME INDEX `ReferenceRule_name_version_key` TO `reference_rule_name_version_key`;
ALTER TABLE `model_version` RENAME INDEX `ModelVersion_approvalStatus_idx` TO `model_version_approval_status_idx`;
ALTER TABLE `model_version` RENAME INDEX `ModelVersion_modelName_version_key` TO `model_version_model_name_version_key`;
ALTER TABLE `model_output` RENAME INDEX `ModelOutput_modelVersionId_createdAt_idx` TO `model_output_model_version_id_created_at_idx`;
ALTER TABLE `model_output` RENAME INDEX `ModelOutput_facilityId_createdAt_idx` TO `model_output_facility_id_created_at_idx`;
ALTER TABLE `model_output` RENAME INDEX `ModelOutput_sourceAdmissionId_idx` TO `model_output_source_admission_id_idx`;
ALTER TABLE `idempotency_record` RENAME INDEX `IdempotencyRecord_facilityId_operation_idx` TO `idempotency_record_facility_id_operation_idx`;
ALTER TABLE `idempotency_record` RENAME INDEX `IdempotencyRecord_clientRecordId_idx` TO `idempotency_record_client_record_id_idx`;
ALTER TABLE `idempotency_record` RENAME INDEX `IdempotencyRecord_userId_key_key` TO `idempotency_record_user_id_key_key`;
ALTER TABLE `sync_event` RENAME INDEX `SyncEvent_facilityId_status_idx` TO `sync_event_facility_id_status_idx`;
ALTER TABLE `sync_event` RENAME INDEX `SyncEvent_clientRecordId_idx` TO `sync_event_client_record_id_idx`;
ALTER TABLE `sync_event` RENAME INDEX `SyncEvent_idempotencyKey_idx` TO `sync_event_idempotency_key_idx`;
ALTER TABLE `audit_log` RENAME INDEX `AuditLog_facilityId_entityType_entityId_idx` TO `audit_log_facility_id_entity_type_entity_id_idx`;
ALTER TABLE `audit_log` RENAME INDEX `AuditLog_userId_createdAt_idx` TO `audit_log_user_id_created_at_idx`;
ALTER TABLE `audit_log` RENAME INDEX `AuditLog_action_createdAt_idx` TO `audit_log_action_created_at_idx`;

-- Recreate foreign keys with lowercase_snake constraint, table, and column names.
ALTER TABLE `refresh_session` ADD CONSTRAINT `refresh_session_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `onboarding_state` ADD CONSTRAINT `onboarding_state_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `onboarding_state` ADD CONSTRAINT `onboarding_state_selected_facility_id_fkey` FOREIGN KEY (`selected_facility_id`) REFERENCES `facility`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `user_settings` ADD CONSTRAINT `user_settings_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `user_settings` ADD CONSTRAINT `user_settings_active_facility_id_fkey` FOREIGN KEY (`active_facility_id`) REFERENCES `facility`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `facility_settings` ADD CONSTRAINT `facility_settings_facility_id_fkey` FOREIGN KEY (`facility_id`) REFERENCES `facility`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `facility_membership` ADD CONSTRAINT `facility_membership_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `facility_membership` ADD CONSTRAINT `facility_membership_facility_id_fkey` FOREIGN KEY (`facility_id`) REFERENCES `facility`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `facility_membership` ADD CONSTRAINT `facility_membership_approved_by_user_id_fkey` FOREIGN KEY (`approved_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `patient` ADD CONSTRAINT `patient_facility_id_fkey` FOREIGN KEY (`facility_id`) REFERENCES `facility`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `admission` ADD CONSTRAINT `admission_patient_id_fkey` FOREIGN KEY (`patient_id`) REFERENCES `patient`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `admission` ADD CONSTRAINT `admission_facility_id_fkey` FOREIGN KEY (`facility_id`) REFERENCES `facility`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `admission` ADD CONSTRAINT `admission_created_by_user_id_fkey` FOREIGN KEY (`created_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `clinical_snapshot` ADD CONSTRAINT `clinical_snapshot_admission_id_fkey` FOREIGN KEY (`admission_id`) REFERENCES `admission`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `clinical_snapshot` ADD CONSTRAINT `clinical_snapshot_entered_by_user_id_fkey` FOREIGN KEY (`entered_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `abg_test` ADD CONSTRAINT `abg_test_admission_id_fkey` FOREIGN KEY (`admission_id`) REFERENCES `admission`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `abg_test` ADD CONSTRAINT `abg_test_entered_by_user_id_fkey` FOREIGN KEY (`entered_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `abg_test` ADD CONSTRAINT `abg_test_reviewed_by_user_id_fkey` FOREIGN KEY (`reviewed_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `ventilator_setting` ADD CONSTRAINT `ventilator_setting_admission_id_fkey` FOREIGN KEY (`admission_id`) REFERENCES `admission`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `ventilator_setting` ADD CONSTRAINT `ventilator_setting_entered_by_user_id_fkey` FOREIGN KEY (`entered_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `airway_device` ADD CONSTRAINT `airway_device_admission_id_fkey` FOREIGN KEY (`admission_id`) REFERENCES `admission`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `airway_device` ADD CONSTRAINT `airway_device_entered_by_user_id_fkey` FOREIGN KEY (`entered_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `humidification_decision` ADD CONSTRAINT `humidification_decision_admission_id_fkey` FOREIGN KEY (`admission_id`) REFERENCES `admission`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `humidification_decision` ADD CONSTRAINT `humidification_decision_confirmed_by_user_id_fkey` FOREIGN KEY (`confirmed_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `daily_ventilation_review` ADD CONSTRAINT `daily_ventilation_review_admission_id_fkey` FOREIGN KEY (`admission_id`) REFERENCES `admission`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `daily_ventilation_review` ADD CONSTRAINT `daily_ventilation_review_reviewed_by_user_id_fkey` FOREIGN KEY (`reviewed_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `outcome` ADD CONSTRAINT `outcome_admission_id_fkey` FOREIGN KEY (`admission_id`) REFERENCES `admission`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `outcome` ADD CONSTRAINT `outcome_entered_by_user_id_fkey` FOREIGN KEY (`entered_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `review_action` ADD CONSTRAINT `review_action_facility_id_fkey` FOREIGN KEY (`facility_id`) REFERENCES `facility`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `review_action` ADD CONSTRAINT `review_action_reviewer_user_id_fkey` FOREIGN KEY (`reviewer_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `dataset_case` ADD CONSTRAINT `dataset_case_facility_id_fkey` FOREIGN KEY (`facility_id`) REFERENCES `facility`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `dataset_case` ADD CONSTRAINT `dataset_case_source_admission_id_fkey` FOREIGN KEY (`source_admission_id`) REFERENCES `admission`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `dataset_case` ADD CONSTRAINT `dataset_case_approved_by_user_id_fkey` FOREIGN KEY (`approved_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `dataset_case` ADD CONSTRAINT `dataset_case_reviewed_by_user_id_fkey` FOREIGN KEY (`reviewed_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `reference_rule` ADD CONSTRAINT `reference_rule_facility_id_fkey` FOREIGN KEY (`facility_id`) REFERENCES `facility`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `reference_rule` ADD CONSTRAINT `reference_rule_approved_by_user_id_fkey` FOREIGN KEY (`approved_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `reference_rule` ADD CONSTRAINT `reference_rule_verified_by_user_id_fkey` FOREIGN KEY (`verified_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `model_output` ADD CONSTRAINT `model_output_model_version_id_fkey` FOREIGN KEY (`model_version_id`) REFERENCES `model_version`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `model_output` ADD CONSTRAINT `model_output_source_admission_id_fkey` FOREIGN KEY (`source_admission_id`) REFERENCES `admission`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `idempotency_record` ADD CONSTRAINT `idempotency_record_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `idempotency_record` ADD CONSTRAINT `idempotency_record_facility_id_fkey` FOREIGN KEY (`facility_id`) REFERENCES `facility`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `sync_event` ADD CONSTRAINT `sync_event_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `sync_event` ADD CONSTRAINT `sync_event_facility_id_fkey` FOREIGN KEY (`facility_id`) REFERENCES `facility`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `audit_log` ADD CONSTRAINT `audit_log_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `audit_log` ADD CONSTRAINT `audit_log_facility_id_fkey` FOREIGN KEY (`facility_id`) REFERENCES `facility`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
