export const MEMBERSHIP_ROLES = Object.freeze({
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  FACILITY_ADMIN: 'FACILITY_ADMIN',
  CLINICIAN: 'CLINICIAN',
  ICU_NURSE: 'ICU_NURSE',
  SPECIALIST_REVIEWER: 'SPECIALIST_REVIEWER',
  RESEARCH_GOVERNANCE_OFFICER: 'RESEARCH_GOVERNANCE_OFFICER',
  MODEL_GOVERNANCE_OFFICER: 'MODEL_GOVERNANCE_OFFICER',
  READ_ONLY_REVIEWER: 'READ_ONLY_REVIEWER',
});

export const MEMBERSHIP_ROLE_VALUES = Object.freeze(Object.values(MEMBERSHIP_ROLES));

export const REQUESTABLE_MEMBERSHIP_ROLE_VALUES = Object.freeze([
  MEMBERSHIP_ROLES.FACILITY_ADMIN,
  MEMBERSHIP_ROLES.CLINICIAN,
  MEMBERSHIP_ROLES.ICU_NURSE,
  MEMBERSHIP_ROLES.SPECIALIST_REVIEWER,
  MEMBERSHIP_ROLES.RESEARCH_GOVERNANCE_OFFICER,
  MEMBERSHIP_ROLES.MODEL_GOVERNANCE_OFFICER,
  MEMBERSHIP_ROLES.READ_ONLY_REVIEWER,
]);

export const READ_ROLES = Object.freeze([
  MEMBERSHIP_ROLES.PLATFORM_ADMIN,
  MEMBERSHIP_ROLES.FACILITY_ADMIN,
  MEMBERSHIP_ROLES.CLINICIAN,
  MEMBERSHIP_ROLES.ICU_NURSE,
  MEMBERSHIP_ROLES.SPECIALIST_REVIEWER,
  MEMBERSHIP_ROLES.RESEARCH_GOVERNANCE_OFFICER,
  MEMBERSHIP_ROLES.MODEL_GOVERNANCE_OFFICER,
  MEMBERSHIP_ROLES.READ_ONLY_REVIEWER,
]);

export const CLINICAL_WRITE_ROLES = Object.freeze([
  MEMBERSHIP_ROLES.CLINICIAN,
  MEMBERSHIP_ROLES.ICU_NURSE,
  MEMBERSHIP_ROLES.SPECIALIST_REVIEWER,
  MEMBERSHIP_ROLES.FACILITY_ADMIN,
]);

export const REVIEW_ROLES = Object.freeze([
  MEMBERSHIP_ROLES.SPECIALIST_REVIEWER,
  MEMBERSHIP_ROLES.RESEARCH_GOVERNANCE_OFFICER,
  MEMBERSHIP_ROLES.FACILITY_ADMIN,
  MEMBERSHIP_ROLES.PLATFORM_ADMIN,
]);

export const DATASET_GOVERNANCE_ROLES = Object.freeze([
  MEMBERSHIP_ROLES.PLATFORM_ADMIN,
  MEMBERSHIP_ROLES.RESEARCH_GOVERNANCE_OFFICER,
]);

export const FACILITY_ADMIN_ROLES = Object.freeze([
  MEMBERSHIP_ROLES.PLATFORM_ADMIN,
  MEMBERSHIP_ROLES.FACILITY_ADMIN,
]);

export const MODEL_GOVERNANCE_ROLES = Object.freeze([
  MEMBERSHIP_ROLES.PLATFORM_ADMIN,
  MEMBERSHIP_ROLES.MODEL_GOVERNANCE_OFFICER,
]);

export const PLATFORM_ADMIN_ROLES = Object.freeze([MEMBERSHIP_ROLES.PLATFORM_ADMIN]);

export const ROLE_PERMISSIONS = Object.freeze({
  [MEMBERSHIP_ROLES.PLATFORM_ADMIN]: Object.freeze([
    'facility:verify',
    'facility:admin',
    'clinical:read',
    'clinical:write',
    'review:write',
    'dataset:export',
    'model:govern',
    'audit:read',
  ]),
  [MEMBERSHIP_ROLES.FACILITY_ADMIN]: Object.freeze([
    'facility:admin',
    'clinical:read',
    'clinical:write',
    'review:write',
    'audit:read',
  ]),
  [MEMBERSHIP_ROLES.CLINICIAN]: Object.freeze(['clinical:read', 'clinical:write']),
  [MEMBERSHIP_ROLES.ICU_NURSE]: Object.freeze(['clinical:read', 'clinical:write']),
  [MEMBERSHIP_ROLES.SPECIALIST_REVIEWER]: Object.freeze([
    'clinical:read',
    'clinical:write',
    'review:write',
  ]),
  [MEMBERSHIP_ROLES.RESEARCH_GOVERNANCE_OFFICER]: Object.freeze([
    'clinical:read',
    'review:write',
    'dataset:export',
  ]),
  [MEMBERSHIP_ROLES.MODEL_GOVERNANCE_OFFICER]: Object.freeze([
    'clinical:read',
    'model:govern',
  ]),
  [MEMBERSHIP_ROLES.READ_ONLY_REVIEWER]: Object.freeze(['clinical:read']),
});

export const getPermissionsForRoles = (roles = []) => [
  ...new Set(roles.flatMap((role) => ROLE_PERMISSIONS[role] || [])),
].sort();
