export const MEMBERSHIP_ROLES = Object.freeze({
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  FACILITY_ADMIN: 'FACILITY_ADMIN',
  CLINICIAN: 'CLINICIAN',
  ICU_NURSE: 'ICU_NURSE',
  SPECIALIST_REVIEWER: 'SPECIALIST_REVIEWER',
  RESEARCH_GOVERNANCE_OFFICER: 'RESEARCH_GOVERNANCE_OFFICER',
  READ_ONLY_REVIEWER: 'READ_ONLY_REVIEWER',
});

export const CLINICAL_WRITE_ROLES = Object.freeze([
  MEMBERSHIP_ROLES.CLINICIAN,
  MEMBERSHIP_ROLES.ICU_NURSE,
  MEMBERSHIP_ROLES.SPECIALIST_REVIEWER,
  MEMBERSHIP_ROLES.FACILITY_ADMIN,
]);

export const REVIEW_ROLES = Object.freeze([
  MEMBERSHIP_ROLES.SPECIALIST_REVIEWER,
  MEMBERSHIP_ROLES.RESEARCH_GOVERNANCE_OFFICER,
  MEMBERSHIP_ROLES.FACILITY_ADMIN,
  MEMBERSHIP_ROLES.PLATFORM_ADMIN,
]);
